const x = 10

try {  // Vai tentar isso

    x = 2

} catch(err) { // Se n√£o conseguir, erro
    console.log(`[ERRO]: ${err}`)
}